version: "3"
services:
  fetcher:
    image: "grab777/taminatherme-crawler:latest"
    environment:
      - DB_PASSWORD=/run/secrets/db_password
    secrets:
      - db_password
secrets:
  db_password:
    file: db_password.txt
