services:
  fetcher:
    build: ./
    environment:
      - DB_PASSWORD=/run/secrets/db_password
      - DB_DATABASE_NAME=tamina
      - DB_HOST=postgres
    secrets:
      - db_password
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - ./temp/db-data:/var/lib/postgresql/data
      - ./pgdata/custom-configs/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./pgdata/custom-configs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
secrets:
  db_password:
    file: db_password.txt
